# Generated by Django 3.2.16 on 2024-03-06 10:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240305_2228'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('post_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
